//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClientApp.Shopping {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Receipt", Namespace="http://schemas.datacontract.org/2004/07/ServerApp")]
    [System.SerializableAttribute()]
    public partial class Receipt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Payment {
            get {
                return this.PaymentField;
            }
            set {
                if ((this.PaymentField.Equals(value) != true)) {
                    this.PaymentField = value;
                    this.RaisePropertyChanged("Payment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Shopping.CustomerSupport")]
    public interface CustomerSupport {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerSupport/Inquire", ReplyAction="http://tempuri.org/CustomerSupport/InquireResponse")]
        int Inquire(string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerSupport/Inquire", ReplyAction="http://tempuri.org/CustomerSupport/InquireResponse")]
        System.Threading.Tasks.Task<int> InquireAsync(string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerSupport/Purchase", ReplyAction="http://tempuri.org/CustomerSupport/PurchaseResponse")]
        WpfClientApp.Shopping.Receipt Purchase(string item, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerSupport/Purchase", ReplyAction="http://tempuri.org/CustomerSupport/PurchaseResponse")]
        System.Threading.Tasks.Task<WpfClientApp.Shopping.Receipt> PurchaseAsync(string item, int quantity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerSupportChannel : WpfClientApp.Shopping.CustomerSupport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerSupportClient : System.ServiceModel.ClientBase<WpfClientApp.Shopping.CustomerSupport>, WpfClientApp.Shopping.CustomerSupport {
        
        public CustomerSupportClient() {
        }
        
        public CustomerSupportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerSupportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerSupportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerSupportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Inquire(string item) {
            return base.Channel.Inquire(item);
        }
        
        public System.Threading.Tasks.Task<int> InquireAsync(string item) {
            return base.Channel.InquireAsync(item);
        }
        
        public WpfClientApp.Shopping.Receipt Purchase(string item, int quantity) {
            return base.Channel.Purchase(item, quantity);
        }
        
        public System.Threading.Tasks.Task<WpfClientApp.Shopping.Receipt> PurchaseAsync(string item, int quantity) {
            return base.Channel.PurchaseAsync(item, quantity);
        }
    }
}
